### ISSUE TITLE
Unable to npm run server

### ISSUE THREAD

**Issue by kilianso** [SolidStateGroup/rio#12]
Hey guys

Trying to install your repo on the Raspberry. But i'm unable to do `npm run server` - It fails and shows a message `Cannot find module '../build/Release/canvas.node'`

I already updated canvas to the latest version. Any ideas?

**Comment by ssg-luke** [comment]
Hey

Sounds like it failed to compile the `node-canvas` native module correctly. Typical reasons for that are missing system dependencies on your RPi. Run `sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++` and make sure that all of those dependencies are install and up to date. After that run `npm rebuild` and try again. Feel free to paste the output of the rebuild here.

In case you haven't noticed it take a look at this too https://github.com/SolidStateGroup/rio/tree/master/rio-server#installation-on-a-raspberry-pi
