### ISSUE TITLE
Use rio with Arduino?

### ISSUE THREAD

**Issue by BarakChamo** [SolidStateGroup/rio#17]
Hi folks,

I'm loving working with rio so far!
Had to tinker with the server a bit to get it to run on a B+ but it's up and running now!

I wanted to ask how can the server be integrated with the Arduino examples in the `firmware` lib? Would it be possible to feed pixel data to `fastled` for example? the `.ino` file references an Ethernet connection but I haven't seen that used anywhere else in the server code.

Any pointers would be appreciated!

**Comment by lukefanning** [comment]
Hi @BarakChamo 
Glad you're having fun using rio! Was there anything you had to do to get it running we haven't covered in our Raspberry Pi guide (https://github.com/SolidStateGroup/rio/tree/master/rio-server#installation-on-a-raspberry-pi)? We're always looking to improve our rio documentation.

It would be possible to re-integrate with an Arduino. To be honest those Arduino files shouldn't really even be there. We haven't pushed pixel data to one for 3 years ^_^. I put up a gist of a file from way back then that might help you get started with creating your Arduino output. https://gist.github.com/ssg-luke/3967324d9da4cc84e28a83d6108af647. It should be possible to feed pixel data over to it but the speed is massively lacking compared to an RPi so you shouldn't expect much of a frame rate at all. There are also usually severe memory limitations using an Arduino that you'll need to bear in mind. Good luck!
