### ISSUE TITLE
Sending... But no image

### ISSUE THREAD

**Issue by AndrewwwGoodwin** [SolidStateGroup/rio#18]
Hey there rio-devs, this project looks awesome, but I'm having trouble getting it driving my 70x34 ws2812 array from my raspberry pi Gpio. 

To give some background:

I've followed the pi install guide for rio-server, installing the dependencies for the project. 

I've gotten strandtest to successfully output to the lights.

Sendtoconsole works and displays the Rio logo in the console. 

I have configured lowlevel-server.py the same way as my strandtest.py, but I'm confused as there are two pins mentioned in lowlevel-server.py.

Once I toggle sendtopi in config, it connects to the listener successfully and says sending {ID} where if it's just the jumble of letters and numbers for the rio gif, however nothing seems to be actually outputting to the led wall my friends and I have built. 

Any help would be greatly appreciated 

Thanks, 
Andrew

**Comment by Logen563** [comment]
I have the same issue :(

**Comment by lukefanning** [comment]
Hi @kingshadowdog If you only have one GPIO pin for data connected to your LED wall then you'd need to edit the lowlevel-server.py script in order to support that.
