### ISSUE TITLE
Server running, but no lights are outputted on RPI 2 model b

### ISSUE THREAD

**Issue by nys99** [SolidStateGroup/rio#59]
Hi, I am having an issue running the rio-server on a Raspberry Pi 2 model B using the Raspberry Pi OS. 

I am able to run ```singlestrandtest.py``` successfully and have my LEDs light up. However, when I run the server with ```sudo npm start``` I get the following output: 
```
Python output: Opening socket...
Python output: Listening...
Python output: accepted connection
Sending 152b3410-e03a-11eb-ab1c-4131ca980b92
```

But the lights do not turn on. Here is my /config/index.js: 
```
/**
 * Created by kylejohnson on 02/10/2016.
 */
module.exports = {
    matrix: {
        width: 150,
        height: 1
    },
    use8bitColors: true,
    sendToConsole: false,
    sendToWebsockets: true,
    sendToPi: true,
    slackToken: '',
    slackChannelName: '',
    twitter: {
        consumer_key:         '',
        consumer_secret:      '',
        access_token:         '',
        access_token_secret:  '',
        timeout_ms:           60*1000,  // optional HTTP request timeout to apply to all requests.
    },
    queueing: true,
    imageInputDisplayTime: 5000, // Only relevant when queueing is enabled,
    watson: true
};
```

Any ideas what the issue might be?

**Comment by lukefanning** [comment]
Hi again, have you configured lowlevel-server.py? You will need to change the parameters in there based on the LED array you are outputting to. By default lowlevel-server.py is configured to output on 2 GPIO pins for maximum performance across a fairly large amount of LEDs. You may need to disable the 2nd channel and comment out the lines that use it in the script. On top of that you may need to change other settings, almost certainly LED_COUNT

**Comment by nys99** [comment]
Hey yes, that did the trick! I only had one string of LEDS so I set the other string LED_COUNT to 0. I also edited config/index.js with the proper matrix dimensions. 

Thank you for your help!
